# Uncomment the next line to define a global platform for your project

workspace 'SensorsThirdParty'
project './Example/Example.xcodeproj'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  
  pod 'SensorsThirdParty/AppsFlyer', :path => '../'

end
